# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talents', '0004_specialtalent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_hash', models.CharField(max_length=32)),
                ('talent_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='talents.Talent')),
                ('talent_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='talents.Talent')),
                ('talent_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='talents.Talent')),
                ('talent_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='talents.Talent')),
                ('talent_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='talents.Talent')),
            ],
        ),
    ]
