# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('loadout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.Loadout')),
            ],
        ),
    ]
