# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builds', '0005_auto_20171120_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='build',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='favorite',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.Build'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
