# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20171122_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='loadout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='builds.Loadout'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='builds.Build'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
