# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_auto_20171122_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='builds.Build'),
        ),
    ]
