# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_auto_20171122_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
