# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_auto_20171123_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('builds', models.ManyToManyField(to='builds.Build')),
            ],
        ),
    ]
