# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_buildset'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
