# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20171120_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='html',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
