# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='type',
            field=models.IntegerField(choices=[(0, 'Melee'), (1, 'Ranged'), (2, 'Support')], default=1),
        ),
    ]
