# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0003_auto_20171121_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champ',
            options={'ordering': ['c_type']},
        ),
        migrations.RenameField(
            model_name='champ',
            old_name='type',
            new_name='c_type',
        ),
    ]
