# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0004_auto_20171121_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='active',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1),
        ),
    ]
