# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=150)),
                ('button', models.IntegerField(choices=[(0, 'Left Mouse'), (1, 'Right Mouse'), (2, 'Q'), (3, 'E'), (4, 'R'), (5, 'F')])),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champs.Champ')),
            ],
        ),
    ]
