# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='button',
            field=models.IntegerField(choices=[(0, 'LMB'), (1, 'RMB'), (2, 'Space'), (3, 'Q'), (4, 'E'), (5, 'R'), (6, 'F')]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='img',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
