# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_auto_20171115_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='img',
        ),
    ]
