# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_remove_spell_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='button',
            field=models.IntegerField(blank=True, choices=[(0, 'LMB'), (1, 'RMB'), (2, 'Space'), (3, 'Q'), (4, 'E'), (5, 'R'), (6, 'F'), (7, 'Special')], null=True),
        ),
    ]
