# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spells', '0002_auto_20171115_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='TalentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='talent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.TalentType'),
        ),
    ]
