# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0001_initial'),
        ('talents', '0003_talent_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champs.Champ')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.Talent')),
            ],
        ),
    ]
