# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_specialtalent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='is_global',
        ),
    ]
