# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_remove_talent_is_global'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['spell']},
        ),
        migrations.AddField(
            model_name='talent',
            name='no_limit',
            field=models.BooleanField(default=False, verbose_name='bypasses spell count limit'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spells.Spell', verbose_name='Spell Image'),
        ),
    ]
