# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0006_auto_20171119_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='modifies_ex',
            field=models.BooleanField(default=False, verbose_name='Modifies EX?'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='no_limit',
            field=models.BooleanField(default=False, verbose_name='Bypass spell count limit'),
        ),
    ]
