# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_auto_20171119_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='talenttype',
            name='dark_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
